print("Second Half Action")
print("==================")
print("")
input("Enter the home team half time score:",)
input("Enter the away team half time score:",)
print("")
input("Enter the home team full time score:",)
input("Enter the away team full time score:",)
print("")
print("The total number of goals scored after halftime is:<<total goals scored>>")
