print("Risky Chair Stacking")
print("====================")
input("Enter the height of 1 chair in cm:",)
input("Enter the overall height of the stacked tower in cm:",)
print()
print("The total number of chair legs present:<<Total chair legs present>>")